# Generated by Django 3.0.6 on 2020-09-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_reviews_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Публікація'),
        ),
    ]
