# Generated by Django 3.0.6 on 2020-09-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Акція', 'verbose_name_plural': 'Акції'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренди'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Колір', 'verbose_name_plural': 'Кольора'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фотографія', 'verbose_name_plural': 'Фотографії'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name': 'Кількість', 'verbose_name_plural': 'Кількості'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Рейтингава зірка', 'verbose_name_plural': 'Рейтингові зірки'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзив', 'verbose_name_plural': 'Отзиви'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Розмір', 'verbose_name_plural': 'Розміри'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Соціальна мережа', 'verbose_name_plural': 'Соціальні мережі'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='action',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Назва акції'),
        ),
        migrations.AddField(
            model_name='action',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Назва акції'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Тег'),
        ),
    ]
