# Generated by Django 3.0.6 on 2020-09-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200914_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Псевдонім'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ru',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Псевдонім'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, verbose_name='Псевдонім'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_ru',
            field=models.SlugField(max_length=255, null=True, verbose_name='Псевдонім'),
        ),
    ]
