# Generated by Django 3.0.6 on 2020-09-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_action_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='value',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Значення'),
        ),
    ]
