# Generated by Django 3.0.6 on 2020-09-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200918_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='action',
        ),
        migrations.CreateModel(
            name='ProductAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Значення')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Action')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Акція продукта',
                'verbose_name_plural': 'Акції продуктів',
            },
        ),
    ]
